# -*- coding: utf-8 -*-
# main_exe/langs/ch.py

CHINESE_DICT = {
    # ── 主介面 ────────────────────────────────────
    'main_title':          (1001, 'FDSB'),
    'no_bots_hint':        (1002, '未找到機器人。點擊「新增機器人」來建立一個。'),
    'new_bot':             (1003, '新增機器人'),
    'discord':             (1004, 'Discord'),
    'github':              (1005, 'GitHub'),

    # ── 機器人建立視窗 ────────────────────────────────
    'name_label':          (1006, '名稱'),
    'token_label':         (1007, 'Token'),
    'name_hint':           (1008, '輸入機器人名稱'),
    'token_hint':          (1009, '輸入機器人 Token'),
    'make':                (1010, '建立'),
    'image_label':         (1011, '圖片'),
    'ok':                  (1012, '確定'),
    'token_required':      (1013, '需要 Token'),
    'name_taken':          (1014, '名稱已被使用\n請選擇其他名稱'),

    # ── 機器人控制面板 ─────────────────────────────────────────
    'state_server':        (1015, '伺服器狀態'),
    'online':              (1016, '上線'),
    'offline':             (1017, '離線'),
    'start':               (1018, '啟動'),
    'stop':                (1019, '停止'),
    'whats_new':           (1020, '最新消息'),
    'no_updates':          (1021, '沒有可用的更新。'),
    'no_file':             (1022, '找不到更新檔案。'),
    'read_error':          (1023, '無法讀取檔案。'),
    'invite_bot':          (1024, '邀請機器人'),
    'back':                (1025, '返回'),
    'main_tab':            (1026, '主頁'),
    'commands_tab':        (1027, '指令'),
    'variables':           (1028, '變數'),
    'settings':            (1029, '設定'),
    'avatar_none':         (1030, '無頭像'),
    'tab_main':            (1117, '主頁'),
    'tab_commands':        (1118, '指令'),
    'tab_variables':       (1119, '變數'),
    'tab_settings':        (1120, '設定'),

    # ── 設定 ─────────────────────────────────────────
    'general_section':     (1031, '一般'),
    'design_section':      (1032, '外觀'),
    'info_section':        (1033, '資訊'),
    'name_project':        (1034, '專案名稱'),
    'token_field':         (1035, '機器人 Token'),
    'bot_name_hint':       (1036, '機器人名稱'),
    'bot_token_hint':      (1037, '機器人 Token'),
    'save':                (1038, '儲存'),
    'language':            (1039, '語言'),
    'wiki':                (1040, 'Wiki'),
    'link':                (1041, '(連結)'),
    'restart_notice':      (1042, '重新啟動中...'),

    # ── 匯出資料 ─────────────────────────────────────
    'export_section':      (1043, '匯出資料'),
    'export_desc':         (1044, '將指令與變數匯出為 ZIP 檔案'),
    'export_zip':          (1045, '匯出為 ZIP'),
    'no_bot_selected':     (1046, '未選擇機器人！'),
    'folders_not_found':   (1047, '找不到資料夾！'),
    'export_failed':       (1048, '匯出失敗！'),

    # ── 危險區域 / 刪除 ────────────────────────────────
    'danger_zone':         (1049, '危險區域'),
    'delete_bot_perm':     (1050, '永久刪除此機器人'),
    'captcha_enter':       (1051, '輸入 3 位數字'),
    'captcha_hint':        (1052, '請輸入上方顯示的 3 位數字'),
    'confirm_delete':      (1053, '確認刪除'),
    'captcha_wrong':       (1054, '代碼錯誤 — 請重試'),

    # ── 主題名稱 ───────────────────────────────────────────
    'system_wh':           (1055, '系統 (淺色)'),
    'system_da':           (1056, '系統 (深色)'),
    'blue_sky':            (1057, '藍色 - 天空'),
    'yellow_bile':         (1058, '黃色 - 金色'),
    'v2_dark':             (1059, '深金色'),

    # ── 指令視圖 ─────────────────────────────────────────
    'commands_slash':      (1060, '/ 指令'),
    'info_command':        (1061, '指令資訊'),
    'command_editor':      (1062, '指令編輯器'),
    'total_lines':         (1063, '行數'),
    'total_text':          (1064, '字元數'),
    'fdscript_hint':       (1065, '# 在此輸入 FDScript 程式碼...'),
    'prefix_label':        (1066, '前綴'),
    'prefix_hint':         (1067, '範例: !cmd'),
    'search':              (1068, '搜尋'),
    'commands':            (1069, '指令'),
    'no_cmds_hint':        (1070, '沒有指令。點擊 + 來建立一個。'),
    'del':                 (1071, '刪除'),
    'name_required':       (1072, '需要名稱'),
    'delete_q':            (1073, '確定刪除？'),
    'delete_confirm':      (1074, '你確定要刪除 "{item_name}" 嗎？\n此動作無法還原。'),
    'dest_event':          (1075, '事件'),
    'dest_cmd':            (1076, '指令'),
    'commands_label':      (1077, '輸入指令名稱'),
    'unsaved_title':       (1113, '未儲存的變更'),
    'unsaved_body':        (1114, '有未儲存的變更。你想在離開前儲存嗎？'),
    'discard':             (1115, '放棄'),

    # ── 舊有鍵值 ────────────────────────────────────────
    'create_file':         (1116, '建立新檔案'),
    'bot_token':           (1078, '機器人 Token'),
    'start_server':        (1079, '啟動伺服器'),
    'stop_server':         (1080, '停止伺服器'),
    'files_list':          (1081, '檔案列表'),
    'run':                 (1082, '執行'),
    'file_name':           (1083, '檔案名稱'),
    'file_content':        (1084, '檔案內容'),
    'variable_name':       (1085, '變數名稱'),
    'variable_value':      (1086, '變數值'),
    'add_variable':        (1087, '新增變數'),
    'no_files':            (1088, '沒有檔案'),
    'no_variables':        (1089, '沒有變數'),
    'enter_token':         (1090, '輸入機器人 Token'),
    'server_status':       (1091, '伺服器狀態'),
    'running':             (1092, '執行中'),
    'stopped':             (1093, '已停止'),
    'edit':                (1094, '編輯'),
    'delete':              (1095, '刪除'),
    'new_file':            (1096, '新檔案'),
    'arabic':              (1097, '阿拉伯語'),
    'english':             (1098, '英語'),
    'confirm':             (1099, '確認'),
    'cancel':              (1100, '取消'),
    'success':             (1101, '成功'),
    'error':               (1102, '錯誤'),
    'file_saved':          (1103, '檔案已儲存'),
    'variable_added':      (1104, '變數已新增'),
    'enter_file_name':     (1105, '輸入檔案名稱'),
    'enter_variable_name': (1106, '輸入變數名稱'),
    'file_prefix':         (1107, '檔案前綴'),
    'enter_prefix':        (1108, '輸入前綴'),
    'prefix':              (1109, '前綴'),
    'edit_prefix':         (1110, '編輯前綴'),
    'prefix_updated':      (1111, '前綴已更新'),
    'toggle_language':     (1112, 'English'),
}