# -*- coding: utf-8 -*-
# main_exe/langs/de.py

GERMAN_DICT = {
    # ── Main UI ───────────────────────────────────────────────
    'main_title':           (1001, 'BCFD-L'),
    'no_bots_hint':         (1002, 'Momentan keine Bots. Tippe auf "Neuer Bot", um einen zu erstellen.'),
    'new_bot':              (1003, 'Neuer Bot'),
    'discord':              (1004, 'Discord'),
    'github':               (1005, 'GitHub'),

    # ── Create Bot Popup ──────────────────────────────────────
    'name_label':           (1006, 'Name'),
    'token_label':          (1007, 'Token'),
    'name_hint':            (1008, 'Gib den Bot-Namen ein'),
    'token_hint':           (1009, 'Gib den Bot-Token ein'),
    'make':                 (1010, 'Erstellen'),
    'image_label':          (1011, 'Bild'),
    'ok':                   (1012, 'OK'),
    'token_required':       (1013, 'Token wird benötigt'),
    'name_taken':           (1014, 'Dieser Name wird bereits verwendet.\nWähle einen anderen Namen.'),

    # ── Bot Dashboard ─────────────────────────────────────────
    'state_server':         (1015, 'Serverstatus'),
    'online':               (1016, 'Online'),
    'offline':              (1017, 'Offline'),
    'start':                (1018, 'Starten'),
    'stop':                 (1019, 'Stoppen'),
    'whats_new':            (1020, "Was gibt es Neues?"),
    'no_updates':           (1021, 'Momentan keine Updates verfügbar.'),
    'no_file':              (1022, 'Update-Datei nicht gefunden.'),
    'read_error':           (1023, 'Update-Datei kann nicht gelesen werden.'),
    'invite_bot':           (1024, 'Bot einladen'),
    'back':                 (1025, 'Zurück'),
    'main_tab':             (1026, 'Hauptmenü'),
    'commands_tab':         (1027, 'Befehle'),
    'variables':            (1028, 'Variablen'),
    'settings':             (1029, 'Einstellungen'),
    'avatar_none':          (1030, 'Keines'),

    # ── Settings ──────────────────────────────────────────────
    'general_section':      (1031, 'Allgemein'),
    'design_section':       (1032, 'Design'),
    'info_section':         (1033, 'Informationen'),
    'name_project':         (1034, 'Projektname'),
    'token_field':          (1035, 'Bot-Token'),
    'bot_name_hint':        (1036, 'Bot-Name'),
    'bot_token_hint':       (1037, 'Bot-Token'),
    'save':                 (1038, 'Speichern'),
    'language':             (1039, 'Sprache'),
    'wiki':                 (1040, 'Wiki'),
    'link':                 (1041, '(Link)'),
    'restart_notice':       (1042, 'Neustart...'),

    # ── Export ────────────────────────────────────────────────
    'export_section':       (1043, 'Bot-Daten exportieren'),
    'export_desc':          (1044, 'Befehle und Variablen als ZIP-Datei exportieren'),
    'export_zip':           (1045, 'Als ZIP exportieren'),
    'no_bot_selected':      (1046, 'Kein Bot ausgewählt!'),
    'folders_not_found':    (1047, 'Ordner nicht gefunden!'),
    'export_failed':        (1048, 'Export fehlgeschlagen!'),

    # ── Danger Zone / Delete ──────────────────────────────────
    'danger_zone':          (1049, 'Gefahrenzone'),
    'delete_bot_perm':      (1050, 'Diesen Bot dauerhaft löschen'),
    'captcha_enter':        (1051, 'Gib 3 Ziffern ein'),
    'captcha_hint':         (1052, 'Gib die oben angezeigten 3 Ziffern ein'),
    'confirm_delete':       (1053, 'Löschung bestätigen'),
    'captcha_wrong':        (1054, 'Code falsch — versuche es erneut'),

    # ── Theme names ───────────────────────────────────────────
    'system_wh':            (1055, 'System (Hell)'),
    'system_da':            (1056, 'System (Dunkel)'),
    'blue_sky':             (1057, 'Blau / Himmel'),
    'yellow_bile':          (1058, 'Gelb / Galle'),
    'v2_dark':              (1059, 'Dunkles Gold'),

    # ── commands_view ─────────────────────────────────────────
    'commands_slash':       (1060, 'Befehle /'),
    'info_command':         (1061, 'Befehls-Infos'),
    'command_editor':       (1062, 'Befehls-Editor'),
    'total_lines':          (1063, 'Zeilen'),
    'total_text':           (1064, 'Zeichen'),
    'fdscript_hint':        (1065, '# FDScript-Code hier...'),
    'prefix_label':         (1066, 'Präfix'),
    'prefix_hint':          (1067, 'Bsp: !befehl'),
    'search':               (1068, 'Suchen'),
    'commands':             (1069, 'Befehle'),
    'no_cmds_hint':         (1070, 'Momentan keine Befehle. Tippe auf +, um einen zu erstellen.'),
    'del':                  (1071, 'Löschen'),
    'name_required':        (1072, 'Name wird benötigt'),
    'delete_q':             (1073, 'Löschen?'),
    'delete_confirm':       (1074, 'Bist du sicher, dass du "{item_name}" löschen möchtest?\nDiese Aktion kann nicht rückgängig gemacht werden.'),
    'dest_event':           (1075, 'Ereignis'),
    'dest_cmd':             (1076, 'Befehl'),

    # ── Old keys ─────────────────────────────────────────────
    'create_file':          (1077, 'Neue Datei erstellen'),
    'bot_token':            (1078, 'Bot-Token'),
    'start_server':         (1079, 'Server starten'),
    'stop_server':          (1080, 'Server stoppen'),
    'files_list':           (1081, 'Dateiliste'),
    'run':                  (1082, 'Speichern und beenden'),
    'file_name':            (1083, 'Dateiname'),
    'file_content':         (1084, 'Dateiinhalt'),
    'variable_name':        (1085, 'Variablenname'),
    'variable_value':       (1086, 'Variablenwert'),
    'add_variable':         (1087, 'Variable hinzufügen'),
    'no_files':             (1088, 'Keine Dateien'),
    'no_variables':         (1089, 'Keine Variablen'),
    'enter_token':          (1090, 'Gib den Bot-Token ein'),
    'server_status':        (1091, 'Serverstatus'),
    'running':              (1092, 'Läuft'),
    'stopped':              (1093, 'Gestoppt'),
    'edit':                 (1094, 'Bearbeiten'),
    'delete':               (1095, 'Löschen'),
    'new_file':             (1096, 'Neue Datei'),
    'arabic':               (1097, 'de'),
    'english':              (1098, 'Deutsch'),
    'confirm':              (1099, 'Bestätigen'),
    'cancel':               (1100, 'Abbrechen'),
    'success':              (1101, 'Erfolg'),
    'error':                 (1102, 'Fehler'),
    'file_saved':           (1103, 'Datei gespeichert'),
    'variable_added':       (1104, 'Variable hinzugefügt'),
    'enter_file_name':      (1105, 'Gib den Dateinamen ein'),
    'enter_variable_name':  (1106, 'Gib den Variablennamen ein'),
    'file_prefix':          (1107, 'Dateipräfix'),
    'enter_prefix':         (1108, 'Gib das Präfix ein (Bsp: !test)'),
    'prefix':               (1109, 'Präfix'),
    'edit_prefix':          (1110, 'Präfix bearbeiten'),
    'prefix_updated':       (1111, 'Präfix aktualisiert'),
    'toggle_language':      (1112, 'Deutsch'),
}