# -*- coding: utf-8 -*-
# main_exe/langs/en.py

ENGLISH_DICT = {
    # ── Main Interface ────────────────────────────────────────
    'main_title':          (1001, 'BCFD-L'),
    'no_bots_hint':        (1002, 'No bots found. Click "New Bot" to create one.'),
    'new_bot':             (1003, 'New Bot'),
    'discord':             (1004, 'Discord'),
    'github':              (1005, 'GitHub'),

    # ── Create Bot Window ─────────────────────────────────────
    'name_label':          (1006, 'Name'),
    'token_label':         (1007, 'Token'),
    'name_hint':           (1008, 'Enter bot name'),
    'token_hint':          (1009, 'Enter bot token'),
    'make':                (1010, 'Create'),
    'image_label':         (1011, 'Image'),
    'ok':                  (1012, 'OK'),
    'token_required':      (1013, 'Token is required'),
    'name_taken':          (1014, 'Name already taken\nChoose a different name'),

    # ── Bot Dashboard ─────────────────────────────────────────
    'state_server':        (1015, 'Server Status'),
    'online':              (1016, 'Online'),
    'offline':             (1017, 'Offline'),
    'start':               (1018, 'Start'),
    'stop':                (1019, 'Stop'),
    'whats_new':           (1020, 'What\'s New'),
    'no_updates':          (1021, 'No updates available.'),
    'no_file':             (1022, 'Updates file not found.'),
    'read_error':          (1023, 'Unable to read file.'),
    'invite_bot':          (1024, 'Invite Bot'),
    'back':                (1025, 'Back'),
    'main_tab':            (1026, 'Main'),
    'commands_tab':        (1027, 'Commands'),
    'variables':           (1028, 'Variables'),
    'settings':            (1029, 'Settings'),
    'avatar_none':         (1030, 'No Avatar'),

    # ── Settings ──────────────────────────────────────────────
    'general_section':     (1031, 'General'),
    'design_section':      (1032, 'Design'),
    'info_section':        (1033, 'Information'),
    'name_project':        (1034, 'Project Name'),
    'token_field':         (1035, 'Bot Token'),
    'bot_name_hint':       (1036, 'Bot Name'),
    'bot_token_hint':      (1037, 'Bot Token'),
    'save':                (1038, 'Save'),
    'language':            (1039, 'Language'),
    'wiki':                (1040, 'Wiki'),
    'link':                (1041, '(Link)'),
    'restart_notice':      (1042, 'Restarting...'),

    # ── Export Data ───────────────────────────────────────────
    'export_section':      (1043, 'Export Data'),
    'export_desc':         (1044, 'Export commands and variables as a ZIP file'),
    'export_zip':          (1045, 'Export ZIP'),
    'no_bot_selected':     (1046, 'No bot selected!'),
    'folders_not_found':   (1047, 'Folders not found!'),
    'export_failed':       (1048, 'Export failed!'),

    # ── Danger Zone / Delete ──────────────────────────────────
    'danger_zone':         (1049, 'Danger Zone'),
    'delete_bot_perm':     (1050, 'Delete this bot permanently'),
    'captcha_enter':       (1051, 'Enter 3 digits'),
    'captcha_hint':        (1052, 'Enter the 3 digits shown above'),
    'confirm_delete':      (1053, 'Confirm Deletion'),
    'captcha_wrong':       (1054, 'Wrong code — Try again'),

    # ── Themes Names ──────────────────────────────────────────
    'system_wh':           (1055, 'System (Light)'),
    'system_da':           (1056, 'System (Dark)'),
    'blue_sky':            (1057, 'Blue - Sky'),
    'yellow_bile':         (1058, 'Yellow - Gold'),
    'v2_dark':             (1059, 'Dark Gold'),

    # ── commands_view ─────────────────────────────────────────
    'commands_slash':      (1060, '/ Commands'),
    'info_command':        (1061, 'Command Info'),
    'command_editor':      (1062, 'Command Editor'),
    'total_lines':         (1063, 'Lines'),
    'total_text':          (1064, 'Characters'),
    'fdscript_hint':       (1065, '# FDScript code here...'),
    'prefix_label':        (1066, 'Prefix'),
    'prefix_hint':         (1067, 'Example: !cmd'),
    'search':              (1068, 'Search'),
    'commands':            (1069, 'Commands'),
    'no_cmds_hint':        (1070, 'No commands found. Click + to create one.'),
    'del':                 (1071, 'Delete'),
    'name_required':       (1072, 'Name is required'),
    'delete_q':            (1073, 'Delete?'),
    'delete_confirm':      (1074, 'Are you sure you want to delete "{item_name}"?\nThis action cannot be undone.'),
    'dest_event':          (1075, 'Event'),
    'dest_cmd':            (1076, 'Command'),
    'commands_label':      (1077, 'Enter command name'),
    'unsaved_title':       (1113, 'Unsaved Changes'),
    'unsaved_body':        (1114, 'There are unsaved changes. Do you want to save them before exiting?'),
    'discard':             (1115, 'Discard'),

    # ── Old Keys ──────────────────────────────────────────────
    'create_file':         (1116, 'Create New File'),
    'bot_token':           (1078, 'Bot Token'),
    'start_server':        (1079, 'Start Server'),
    'stop_server':         (1080, 'Stop Server'),
    'files_list':          (1081, 'Files List'),
    'run':                 (1082, 'Run'),
    'file_name':           (1083, 'File Name'),
    'file_content':        (1084, 'File Content'),
    'variable_name':       (1085, 'Variable Name'),
    'variable_value':      (1086, 'Variable Value'),
    'add_variable':        (1087, 'Add Variable'),
    'no_files':            (1088, 'No files'),
    'no_variables':        (1089, 'No variables'),
    'enter_token':         (1090, 'Enter bot token'),
    'server_status':       (1091, 'Server Status'),
    'running':             (1092, 'Running'),
    'stopped':             (1093, 'Stopped'),
    'edit':                (1094, 'Edit'),
    'delete':              (1095, 'Delete'),
    'new_file':            (1096, 'New File'),
    'arabic':              (1097, 'Arabic'),
    'english':             (1098, 'English'),
    'confirm':             (1099, 'Confirm'),
    'cancel':              (1100, 'Cancel'),
    'success':             (1101, 'Success'),
    'error':               (1102, 'Error'),
    'file_saved':          (1103, 'File saved'),
    'variable_added':      (1104, 'Variable added'),
    'enter_file_name':     (1105, 'Enter file name'),
    'enter_variable_name': (1106, 'Enter variable name'),
    'file_prefix':         (1107, 'File Prefix'),
    'enter_prefix':        (1108, 'Enter prefix'),
    'prefix':              (1109, 'Prefix'),
    'edit_prefix':         (1110, 'Edit Prefix'),
    'prefix_updated':      (1111, 'Prefix updated'),
    'toggle_language':     (1112, 'English'), 
}