# -*- coding: utf-8 -*-
# main_exe/langs/fr.py

FRENCH_DICT = {
    # ── Interface principale ──────────────────────────────────
    'main_title':          (1001, 'FDSB'),
    'no_bots_hint':        (1002, 'Aucun bot trouvé. Cliquez sur "Nouveau bot" pour en créer un.'),
    'new_bot':             (1003, 'Nouveau bot'),
    'discord':             (1004, 'Discord'),
    'github':              (1005, 'GitHub'),

    # ── Fenêtre de création de bot ────────────────────────────
    'name_label':          (1006, 'Nom'),
    'token_label':         (1007, 'Jeton (Token)'),
    'name_hint':           (1008, 'Entrez le nom du bot'),
    'token_hint':          (1009, 'Entrez le jeton du bot'),
    'make':                (1010, 'Créer'),
    'image_label':         (1011, 'Image'),
    'ok':                  (1012, 'OK'),
    'token_required':      (1013, 'Le jeton est requis'),
    'name_taken':          (1014, 'Nom déjà pris\nChoisissez un autre nom'),

    # ── Tableau de bord du bot ────────────────────────────────
    'state_server':        (1015, 'État du serveur'),
    'online':              (1016, 'En ligne'),
    'offline':             (1017, 'Hors ligne'),
    'start':               (1018, 'Démarrer'),
    'stop':                (1019, 'Arrêter'),
    'whats_new':           (1020, 'Quoi de neuf'),
    'no_updates':          (1021, 'Aucune mise à jour disponible.'),
    'no_file':             (1022, 'Fichier de mises à jour introuvable.'),
    'read_error':          (1023, 'Impossible de lire le fichier.'),
    'invite_bot':          (1024, 'Inviter le bot'),
    'back':                (1025, 'Retour'),
    'main_tab':            (1026, 'Principal'),
    'commands_tab':        (1027, 'Commandes'),
    'variables':           (1028, 'Variables'),
    'settings':            (1029, 'Paramètres'),
    'avatar_none':         (1030, 'Sans avatar'),
    'tab_main':            (1117, 'Principal'),
    'tab_commands':        (1118, 'Commandes'),
    'tab_variables':       (1119, 'Variables'),
    'tab_settings':        (1120, 'Paramètres'),

    # ── Paramètres ────────────────────────────────────────────
    'general_section':     (1031, 'Général'),
    'design_section':      (1032, 'Conception'),
    'info_section':        (1033, 'Informations'),
    'name_project':        (1034, 'Nom du projet'),
    'token_field':         (1035, 'Jeton du bot'),
    'bot_name_hint':       (1036, 'Nom du bot'),
    'bot_token_hint':      (1037, 'Jeton du bot'),
    'save':                (1038, 'Enregistrer'),
    'language':            (1039, 'Langue'),
    'wiki':                (1040, 'Wiki'),
    'link':                (1041, '(Lien)'),
    'restart_notice':      (1042, 'Redémarrage en cours...'),

    # ── Exporter les données ──────────────────────────────────
    'export_section':      (1043, 'Exporter les données'),
    'export_desc':         (1044, 'Exporter les commandes et variables en fichier ZIP'),
    'export_zip':          (1045, 'Exporter en ZIP'),
    'no_bot_selected':     (1046, 'Aucun bot sélectionné !'),
    'folders_not_found':   (1047, 'Dossiers introuvables !'),
    'export_failed':       (1048, 'Échec de l\'exportation !'),

    # ── Zone de danger / Suppression ──────────────────────────
    'danger_zone':         (1049, 'Zone de danger'),
    'delete_bot_perm':     (1050, 'Supprimer ce bot définitivement'),
    'captcha_enter':       (1051, 'Entrez 3 chiffres'),
    'captcha_hint':        (1052, 'Entrez les 3 chiffres ci-dessus'),
    'confirm_delete':      (1053, 'Confirmer la suppression'),
    'captcha_wrong':       (1054, 'Code incorrect — Réessayez'),

    # ── Noms des thèmes ───────────────────────────────────────
    'system_wh':           (1055, 'Système (Clair)'),
    'system_da':           (1056, 'Système (Sombre)'),
    'blue_sky':            (1057, 'Bleu - Ciel'),
    'yellow_bile':         (1058, 'Jaune - Or'),
    'v2_dark':             (1059, 'Or Sombre'),

    # ── commands_view ─────────────────────────────────────────
    'commands_slash':      (1060, 'Commandes /'),
    'info_command':        (1061, 'Infos sur la commande'),
    'command_editor':      (1062, 'Éditeur de commande'),
    'total_lines':         (1063, 'Lignes'),
    'total_text':          (1064, 'Caractères'),
    'fdscript_hint':       (1065, '# Code FDScript ici...'),
    'prefix_label':        (1066, 'Préfixe'),
    'prefix_hint':         (1067, 'Exemple : !cmd'),
    'search':              (1068, 'Rechercher'),
    'commands':            (1069, 'Commandes'),
    'no_cmds_hint':        (1070, 'Aucune commande. Cliquez sur + pour en créer une.'),
    'del':                 (1071, 'Supprimer'),
    'name_required':       (1072, 'Le nom est requis'),
    'delete_q':            (1073, 'Supprimer ?'),
    'delete_confirm':      (1074, 'Êtes-vous sûr de vouloir supprimer "{item_name}" ?\nCette action est irréversible.'),
    'dest_event':          (1075, 'Événement'),
    'dest_cmd':            (1076, 'Commande'),
    'commands_label':      (1077, 'Entrez le nom de la commande'),
    'unsaved_title':       (1113, 'Modifications non enregistrées'),
    'unsaved_body':        (1114, 'Il y a des modifications non enregistrées. Voulez-vous les enregistrer avant de quitter ?'),
    'discard':             (1115, 'Ignorer'),

    # ── Anciennes clés ────────────────────────────────────────
    'create_file':         (1116, 'Créer un nouveau fichier'),
    'bot_token':           (1078, 'Jeton du bot'),
    'start_server':        (1079, 'Démarrer le serveur'),
    'stop_server':         (1080, 'Arrêter le serveur'),
    'files_list':          (1081, 'Liste des fichiers'),
    'run':                 (1082, 'Exécuter'),
    'file_name':           (1083, 'Nom du fichier'),
    'file_content':        (1084, 'Contenu du fichier'),
    'variable_name':       (1085, 'Nom de la variable'),
    'variable_value':      (1086, 'Valeur de la variable'),
    'add_variable':        (1087, 'Ajouter une variable'),
    'no_files':            (1088, 'Aucun fichier'),
    'no_variables':        (1089, 'Aucune variable'),
    'enter_token':         (1090, 'Entrez le jeton du bot'),
    'server_status':       (1091, 'État du serveur'),
    'running':             (1092, 'En cours d\'exécution'),
    'stopped':             (1093, 'Arrêté'),
    'edit':                (1094, 'Modifier'),
    'delete':              (1095, 'Supprimer'),
    'new_file':            (1096, 'Nouveau fichier'),
    'arabic':              (1097, 'Arabe'),
    'english':             (1098, 'Anglais'),
    'confirm':             (1099, 'Confirmer'),
    'cancel':              (1100, 'Annuler'),
    'success':             (1101, 'Succès'),
    'error':               (1102, 'Erreur'),
    'file_saved':          (1103, 'Fichier enregistré'),
    'variable_added':      (1104, 'Variable ajoutée'),
    'enter_file_name':     (1105, 'Entrez le nom du fichier'),
    'enter_variable_name': (1106, 'Entrez le nom de la variable'),
    'file_prefix':         (1107, 'Préfixe du fichier'),
    'enter_prefix':        (1108, 'Entrez le préfixe'),
    'prefix':              (1109, 'Préfixe'),
    'edit_prefix':         (1110, 'Modifier le préfixe'),
    'prefix_updated':      (1111, 'Préfixe mis à jour'),
    'toggle_language':     (1112, 'English'),
}