# -*- coding: utf-8 -*-
# main_exe/langs/tr.py

TURKISH_DICT = {
    # ── Ana Arayüz ────────────────────────────────────
    'main_title':          (1001, 'BCFD-L'),
    'no_bots_hint':        (1002, 'Bot bulunamadı. Oluşturmak için "Yeni Bot"a tıklayın.'),
    'new_bot':             (1003, 'Yeni Bot'),
    'discord':             (1004, 'Discord'),
    'github':              (1005, 'GitHub'),

    # ── Bot Oluşturma Penceresi ────────────────────────────────
    'name_label':          (1006, 'İsim'),
    'token_label':         (1007, 'Token'),
    'name_hint':           (1008, 'Bot ismini girin'),
    'token_hint':          (1009, 'Bot tokenini girin'),
    'make':                (1010, 'Oluştur'),
    'image_label':         (1011, 'Resim'),
    'ok':                  (1012, 'Tamam'),
    'token_required':      (1013, 'Token gereklidir'),
    'name_taken':          (1014, 'İsim zaten kullanımda\nBaşka bir isim seçin'),

    # ── Bot Kontrol Paneli ─────────────────────────────────────────
    'state_server':        (1015, 'Sunucu durumu'),
    'online':              (1016, 'Çevrimiçi'),
    'offline':             (1017, 'Çevrimdışı'),
    'start':               (1018, 'Başlat'),
    'stop':                (1019, 'Durdur'),
    'whats_new':           (1020, 'Yenilikler'),
    'no_updates':          (1021, 'Güncelleme yok.'),
    'no_file':             (1022, 'Güncelleme dosyası bulunamadı.'),
    'read_error':          (1023, 'Dosya okunamadı.'),
    'invite_bot':          (1024, 'Botu davet et'),
    'back':                (1025, 'Geri'),
    'main_tab':            (1026, 'Ana Sayfa'),
    'commands_tab':        (1027, 'Komutlar'),
    'variables':           (1028, 'Değişkenler'),
    'settings':            (1029, 'Ayarlar'),
    'avatar_none':         (1030, 'Avatar yok'),

    # ── Ayarlar ─────────────────────────────────────────
    'general_section':     (1031, 'Genel'),
    'design_section':      (1032, 'Tasarım'),
    'info_section':        (1033, 'Bilgi'),
    'name_project':        (1034, 'Proje ismi'),
    'token_field':         (1035, 'Bot Tokeni'),
    'bot_name_hint':       (1036, 'Bot ismi'),
    'bot_token_hint':      (1037, 'Bot tokeni'),
    'save':                (1038, 'Kaydet'),
    'language':            (1039, 'Dil'),
    'wiki':                (1040, 'Wiki'),
    'link':                (1041, '(Bağlantı)'),
    'restart_notice':      (1042, 'Yeniden başlatılıyor...'),

    # ── Veri Dışa Aktarma ─────────────────────────────────────
    'export_section':      (1043, 'Veriyi dışa aktar'),
    'export_desc':         (1044, 'Komutları ve değişkenleri ZIP olarak dışa aktar'),
    'export_zip':          (1045, 'ZIP olarak aktar'),
    'no_bot_selected':     (1046, 'Bot seçilmedi!'),
    'folders_not_found':   (1047, 'Klasörler bulunamadı!'),
    'export_failed':       (1048, 'Dışa aktarma başarısız!'),

    # ── Tehlike Bölgesi / Silme ────────────────────────────────
    'danger_zone':         (1049, 'Tehlike bölgesi'),
    'delete_bot_perm':     (1050, 'Bu botu kalıcı olarak sil'),
    'captcha_enter':       (1051, '3 rakam girin'),
    'captcha_hint':        (1052, 'Yukarıda gösterilen 3 rakamı girin'),
    'confirm_delete':      (1053, 'Silmeyi onayla'),
    'captcha_wrong':       (1054, 'Yanlış kod — Tekrar deneyin'),

    # ── Tema İsimleri ───────────────────────────────────────────
    'system_wh':           (1055, 'Sistem (Açık)'),
    'system_da':           (1056, 'Sistem (Koyu)'),
    'blue_sky':            (1057, 'Mavi - Gökyüzü'),
    'yellow_bile':         (1058, 'Sarı - Altın'),
    'v2_dark':             (1059, 'Koyu Altın'),

    # ── Komut Görünümü ─────────────────────────────────────────
    'commands_slash':      (1060, '/ Komutlar'),
    'info_command':        (1061, 'Komut bilgisi'),
    'command_editor':      (1062, 'Komut düzenleyici'),
    'total_lines':         (1063, 'Satır'),
    'total_text':          (1064, 'Karakter'),
    'fdscript_hint':       (1065, '# FDScript kodunu buraya yazın...'),
    'prefix_label':        (1066, 'Önek'),
    'prefix_hint':         (1067, 'Örnek: !cmd'),
    'search':              (1068, 'Ara'),
    'commands':            (1069, 'Komutlar'),
    'no_cmds_hint':        (1070, 'Komut yok. Bir tane oluşturmak için + butonuna tıklayın.'),
    'del':                 (1071, 'Sil'),
    'name_required':       (1072, 'İsim gereklidir'),
    'delete_q':            (1073, 'Silinsin mi?'),
    'delete_confirm':      (1074, '"{item_name}" ögesini silmek istediğinize emin misiniz?\nBu işlem geri alınamaz.'),
    'dest_event':          (1075, 'Olay'),
    'dest_cmd':            (1076, 'Komut'),
    'commands_label':      (1077, 'Komut ismini girin'),
    'unsaved_title':       (1113, 'Kaydedilmemiş değişiklikler'),
    'unsaved_body':        (1114, 'Kaydedilmemiş değişiklikler var. Çıkmadan önce kaydetmek ister misiniz?'),
    'discard':             (1115, 'Vazgeç'),

    # ── Eski Anahtarlar ────────────────────────────────────────
    'create_file':         (1116, 'Yeni dosya oluştur'),
    'bot_token':           (1078, 'Bot Tokeni'),
    'start_server':        (1079, 'Sunucuyu başlat'),
    'stop_server':         (1080, 'Sunucuyu durdur'),
    'files_list':          (1081, 'Dosya listesi'),
    'run':                 (1082, 'Çalıştır'),
    'file_name':           (1083, 'Dosya ismi'),
    'file_content':        (1084, 'Dosya içeriği'),
    'variable_name':       (1085, 'Değişken ismi'),
    'variable_value':      (1086, 'Değişken değeri'),
    'add_variable':        (1087, 'Değişken ekle'),
    'no_files':            (1088, 'Dosya yok'),
    'no_variables':        (1089, 'Değişken yok'),
    'enter_token':         (1090, 'Bot tokenini girin'),
    'server_status':       (1091, 'Sunucu durumu'),
    'running':             (1092, 'Çalışıyor'),
    'stopped':             (1093, 'Durduruldu'),
    'edit':                (1094, 'Düzenle'),
    'delete':              (1095, 'Sil'),
    'new_file':            (1096, 'Yeni dosya'),
    'arabic':              (1097, 'Arapça'),
    'english':             (1098, 'İngilizce'),
    'confirm':             (1099, 'Onayla'),
    'cancel':              (1100, 'İptal'),
    'success':             (1101, 'Başarılı'),
    'error':               (1102, 'Hata'),
    'file_saved':          (1103, 'Dosya kaydedildi'),
    'variable_added':      (1104, 'Değişken eklendi'),
    'enter_file_name':     (1105, 'Dosya ismini girin'),
    'enter_variable_name': (1106, 'Değişken ismini girin'),
    'file_prefix':         (1107, 'Dosya öneki'),
    'enter_prefix':        (1108, 'Önek girin'),
    'prefix':              (1109, 'Önek'),
    'edit_prefix':         (1110, 'Öneki düzenle'),
    'prefix_updated':      (1111, 'Önek güncellendi'),
    'toggle_language':     (1112, 'English'),
}